import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/shared/providers";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WallpaperNext",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <Header />
          {/* <main className="max-w-7xl mx-auto"> */}
          {children}
          {/* </main> */}
        </Providers>
      </body>
    </html>
  );
}
